server.port: 8090

<<<<<<< HEAD
server.port: 8020
=======
spring.mvc.pathmatch.matching-strategy: ant-path-matcher
>>>>>>> 59e7b9e (Ticket_Booking:)

spring:
  datasource:
    url: jdbc:mysql://localhost/ticket_booking
    username: root
<<<<<<< HEAD
    password: dhanesh@22

  jpa:
    hibernate.ddl-auto: update
    show_sql: true
    use_sql_comments: true
    format_sql: true
    event:
      merge:
        entity_copy_observer: allow
    database-platform=org:
      hibernate:
        dialect: MySQL5Dialect
=======
    password: harini@04

  jpa:
#    hibernate.ddl-auto: update
#    show_sql: true
#    use_sql_comments: true
#    format_sql: true
#    event:
#      merge:
#        entity_copy_observer: allow
    database-platform=org:
      hibernate:
        dialect: MySQL5InnoDBDialect
>>>>>>> 59e7b9e (Ticket_Booking:)




