spring.mvc.pathmatch.matching-strategy: ant_path_matcher
server.port: 2022
spring:
  database-platform=org:
    hibernate:
      dialect: MySQL5InnoDBDialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost/bk

    username: root
    password: dhanesh@22

    flyway:baselineOnMigrate : true

  main:
    allow-circular-references: true





