
server.port: 8020

spring.mvc.pathmatch.matching-strategy: ant-path-matcher

spring:
  datasource:
    url: jdbc:mysql://localhost/ticket_booking
    username: root
    password: siva2001
  main:
    allow-circular-reference: true
  jpa:
    database-platform=org:
      hibernate:
        dialect: MySQL5InnoDBDialect
        
    main:
    allow-circular-references: true






