spring.mvc.pathmatch.matching-strategy: ant_path_matcher
server.port: 8020

spring:
  datasource:
    url: jdbc:mysql://localhost/ticket_booking
    username: root
    password: dhanesh@22
    database-platform=org:
      hibernate:
        dialect: MySQL5Dialect




