
server.port: 8020
=======
spring.mvc.pathmatch.matching-strategy: ant-path-matcher


spring:
  datasource:
    url: jdbc:mysql://localhost/ticket_booking
    username: root

    password: dhanesh@22
    database-platform=org:
      hibernate:
        dialect: MySQL5Dialect



#    hibernate.ddl-auto: update
#    show_sql: true
#    use_sql_comments: true
#    format_sql: true
#    event:
#      merge:
#        entity_copy_observer: allow





