spring.mvc.pathmatch.matching-strategy: ant_path_matcher
server.port: 2022
spring:
  database-platform=org:
    hibernate:
      dialect: MySQL5InnoDBDialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/book
    username: root
    password: siva2001
  main:
    allow-circular-references: true





