CREATE TABLE genre (
  id BIGINT AUTO_INCREMENT NOT NULL,
   genre_name VARCHAR(255) NULL,
   CONSTRAINT pk_genre PRIMARY KEY (id)
);
CREATE TABLE language (
  id BIGINT AUTO_INCREMENT NOT NULL,
   language VARCHAR(255) NULL,
   CONSTRAINT pk_language PRIMARY KEY (id)
);
CREATE TABLE cast (
  id BIGINT AUTO_INCREMENT NOT NULL,
   cast_name VARCHAR(255) NULL,
   cast_role VARCHAR(255) NULL,
   CONSTRAINT pk_cast PRIMARY KEY (id)
);