
#spring.mvc.pathmatch.matching-strategy : ant_path_matcher
server.port: 8090

spring:
  database-platform=org:
    hibernate:
      dialect: MySQL5InnoDBDialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_ticket_booking
    username: root
    password: harini@04


#    Set flyway:
#      Outoforder: true


